var suggestions = [
    "iPhone 12 Pro Max",
    "SamSung Galaxy S20 Plus",
    "SamSung Galaxy A51",
    "SamSung Galaxy M11",
    "SamSung Galaxy A31",
    "ip11",
    "ipad 10.2",
    "SamSung Galaxy A11",
    "SamSung Galaxy A20s",
    "iPhone 11 Pro Max",
    "Vsmart Active 3",
    "Realme 3 Pro",
    "Galaxy Note 10 plus",
    "OPPO A9",
    "iPhone SE 64GB",
    "Xiaomi redmi note 8 pro",
    "VIVO Y91C",
    "Realme C3i",
    "Realme 5 Pro",
    "Xiaomi k20",
    "Apple",
    "ip10",
    "ip8 plus",
]